version: "3"
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_PASS=$DB_PASS
      - EMAIL=$EMAIL
      - GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
      - HOST=$HOST
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BUCKET_NAME=$BUCKET_NAME
    depends_on:
      - db
  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$DB_PASS


volumes:
  postgres_data: